### ISSUE TITLE
Extra elements in JSON payload are not rejected

### ISSUE THREAD

**Issue by Stwissel** [node-red-tools/node-red-contrib-openapi#114]
I have a schema:

```yaml
title: Root Type for TrafficLight
description: ''
required:
    - color
    - location
    - type
type: object
properties:
    color:
        description: 'Color of the traffic light, Red, Yellow, Green'
        enum:
            - red
            - yellow
            - green
        type: string
    type:
        description: Who is it for
        enum:
            - pedestrian
            - bicycle
            - motorvehicles
        type: string
    location:
        description: Some address String
        type: string
example:
    color: red
    type: pedestrian
    location: 21nd Street
```

when I submit: 

```
 {
        "color": "red",
        "type": "pedestrian",
        "location": "21nd Street",
        "lamppost" : 42
    }
```

I would expect an error due to an undefined element `lamppost`, but submission happens
